version: '3.8'

services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 12G
          cpus: '1.5'
    networks:
      - rag-network
    hostname: ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 15s
      timeout: 15s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - CONFIG_PATH=/app/config/config.yaml
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - rag-network
    command: ["sh", "-c", "cd /app && python -m src.backend.main"]

  slack-bot:
    build:
      context: .
      dockerfile: Dockerfile.slack
    environment:
      - RAG_API_URL=http://backend:8000
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  ollama_data:
