apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  config.yaml: |-
    llm:
      ollama:
        base_url: http://{{ .Values.ollama.name }}:{{ .Values.ollama.service.port }}
        model_name: {{ .Values.backend.config.llm.ollama.model_name }}
        parameters:
          temperature: {{ .Values.backend.config.llm.ollama.parameters.temperature }}
          top_p: {{ .Values.backend.config.llm.ollama.parameters.top_p }}
          max_tokens: {{ .Values.backend.config.llm.ollama.parameters.max_tokens }}
    embeddings:
      model_name: {{ .Values.backend.config.embeddings.model_name }}
      vector_db_path: {{ .Values.backend.config.embeddings.vector_db_path }}
    api:
      host: {{ .Values.backend.config.api.host }}
      port: {{ .Values.backend.config.api.port }}
      cors_origins:
      {{- range .Values.backend.config.api.cors_origins }}
        - {{ . }}
      {{- end }}
    slack:
      bot_token: ${SLACK_BOT_TOKEN}
      app_token: ${SLACK_APP_TOKEN}
      signing_secret: ${SLACK_SIGNING_SECRET}
