{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  GITHUB_TOKEN: {{ .Values.secrets.values.GITHUB_TOKEN | b64enc | quote }}
  SLACK_BOT_TOKEN: {{ .Values.secrets.values.SLACK_BOT_TOKEN | b64enc | quote }}
  SLACK_APP_TOKEN: {{ .Values.secrets.values.SLACK_APP_TOKEN | b64enc | quote }}
  SLACK_SIGNING_SECRET: {{ .Values.secrets.values.SLACK_SIGNING_SECRET | b64enc | quote }}
{{- end }}
