apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-zscaler-cert
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  zscaler.crt: |-
